// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwlCMTCyHrlH5RZYVrYlxjsOJIIg9t1-c',
    appId: '1:359250921036:web:5c6bbd3bb9ab18fcb196e9',
    messagingSenderId: '359250921036',
    projectId: 'chats-3c78b',
    authDomain: 'chats-3c78b.firebaseapp.com',
    storageBucket: 'chats-3c78b.appspot.com',
    measurementId: 'G-7TH84QMYDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChhLu92wnbVfsN6FdUGo3Ykh1sr9dLN1Y',
    appId: '1:359250921036:android:b96e2a118d7d7b21b196e9',
    messagingSenderId: '359250921036',
    projectId: 'chats-3c78b',
    storageBucket: 'chats-3c78b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmb7lvLVp4lXrb_X7caFDs3OiSqyw_zN0',
    appId: '1:359250921036:ios:b1b4151ca048c5fbb196e9',
    messagingSenderId: '359250921036',
    projectId: 'chats-3c78b',
    storageBucket: 'chats-3c78b.appspot.com',
    iosClientId: '359250921036-teaqpkeq5r6av4h0gjbtirnbpe24gq67.apps.googleusercontent.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmb7lvLVp4lXrb_X7caFDs3OiSqyw_zN0',
    appId: '1:359250921036:ios:b1b4151ca048c5fbb196e9',
    messagingSenderId: '359250921036',
    projectId: 'chats-3c78b',
    storageBucket: 'chats-3c78b.appspot.com',
    iosClientId: '359250921036-teaqpkeq5r6av4h0gjbtirnbpe24gq67.apps.googleusercontent.com',
    iosBundleId: 'com.example.chats',
  );
}
